
# Site settings
title: vivek mumbles
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    A simple blog.
exclude: [README.md, Makefile, LICENSE]
baseurl: ""
url: http://vivekmumbles.io
permalink: /:categories/:title
gems: [jekyll-paginate]
paginate: 2
paginate_path: posts/page:num
# pagination: true

twitter_username: vivekmumbles
github_username:  vivekmumbles

# Build settings
markdown: kramdown
